IWLWIFI Vendor command support
projectceladon/libwifihal-intel pull request #4
Opened 2019-04-24 07:55 UTC by amritara

Adding Vendor command support in Intel WiFi HAL.

Tracked-On: OAM-79910
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
Signed-off-by: Amrita Raju <amrita.raju@intel.com>

@JeevakaPrabu @sgnanase @swaroopbalan

2019-04-25 03:35 UTC, JeevakaPrabu requested changes
Commit message needs to be detail the vendor command support added

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +	attr_policy[IWL_MVM_VENDOR_ATTR_FW_VER].type =	NLA_STRING;
Remove 1 extra blank space between = and NLA_STRING

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +	if(nla_parse_nested(cap, MAX_IWL_MVM_VENDOR_ATTR, data, attr_policy)) {
Introduce a space between if and (

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +	if (!cap[IWL_MVM_VENDOR_ATTR_FW_VER]) {
Limit the number of characters/line to 100 characters

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +	nla_strlcpy(code, cap[IWL_MVM_VENDOR_ATTR_FW_VER], 50);	//copy attribute to a sized string
Limit the number of characters/line to 100 characters

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +
Remove extra blank line

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +	       	NULL, 0, 0, get_fw_handler, buf);
Can we rename it to get_fw_version_handler?

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +        if(nla_parse_nested(cap, MAX_IWL_MVM_VENDOR_ATTR, data, attr_policy)) {
Introduce a space between if and (

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +        nla_strlcpy(code, cap[IWL_MVM_VENDOR_ATTR_DRV_VER], 50); //copy attribute to a sized string
Instead of number can we use MACRO?

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/driver_if.cpp
> +
Remove extra blank line

2019-04-25 03:35 UTC, JeevakaPrabu commented on lib/wifi_hal.cpp
> +        if ((WIFI_INFO_INVALID(iface, __func__)) || !(buffer && (buffer_size > 0)))
Indentation doesn't seem to be correct.

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +#include "includes.h"
Copy right information missing

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/iwl_vendor_cmd_copy.h
> +	IWL_MVM_VENDOR_CMD_SET_COUNTRY,
IWL_MVM_VENDOR_CMD_SET_COUNTRY can't be upstreamed. So, this needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/iwl_vendor_cmd_copy.h
> + * @IWL_MVM_VENDOR_ATTR_COUNTRY: MCC to set, for regulatory information (u16)
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/iwl_vendor_cmd_copy.h
> +	IWL_MVM_VENDOR_ATTR_COUNTRY,
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/iwl_vendor_cmd_copy.h
> +#define IWL_MVM_VENDOR_FILTER_GTK IWL_MVM_VENDOR_ATTR_FILTER_GTK
Above 2 definitions not needed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/iwl_vendor_cmd_copy.h
> + * @IWL_MVM_VENDOR_CMD_SET_COUNTRY: set a new mcc regulatory information
SET_COUNTRY code can't be up-streamed. So needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +		ret = wpa_driver_nl80211_set_country_code(priv, cmd + 8);
Remove this and add it to next else loop

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +	} else if (os_strcasecmp(cmd, "LINKSPEED") == 0) {
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +		   (os_strcasecmp(cmd, "RSSI-APPROX") == 0)) {
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +static int wpa_driver_nl80211_set_country_code(void *priv, char *cmd)
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +static int nl80211_get_link_signal(struct wpa_driver_nl80211_data *drv,
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +static int get_link_signal(struct nl_msg *msg, void *arg)
Needs to be removed

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/driver_cmd_nl80211.c
> +#include "iwl_vendor_cmd_copy.h"
Recheck the need for above header files

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wifi.c
> +/*
This file is not needed at all. Could you remove it?

2019-04-25 03:35 UTC, JeevakaPrabu commented on wifi/wpa_supplicant_8_lib/Android.mk
> +#
Instead of having it under wifi we can directly have it under wpa_supplicant_8_lib

2019-05-20 12:21 UTC, JeevakaPrabu approved these changes

2019-05-22 03:47 UTC, swaroopbalan approved these changes

2019-05-22 07:15 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/509

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2019-05-22 15:49 UTC, sysopenci reviewed
PR integrated into 'premerge' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/245

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2019-05-23 03:30 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/246

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2019-05-27 06:43 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/516

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2019-05-27 06:54 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/249

Done by "Badrappan, Jeevaka" <jeevaka.badrappan@intel.com>

2019-05-28 04:01 UTC, merged

2019-05-28 06:39 UTC, sysopenci commented
cactus finished building and testing your changes

It was requested for merge by "Badrappan, Jeevaka" jeevaka.badrappan@intel.com

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/825